project_id = "tpdpfsouhqjlchkibdwe"

[functions.generate-clarification-questions]
verify_jwt = true

[functions.submit-clarification-answers]
verify_jwt = true

[functions.calculate-fit-score]
verify_jwt = true

[functions.process-investment]
verify_jwt = true
